Console.WriteLine("==================================");
Console.WriteLine("Рецепт: Идеальный утренний кофе");
Console.WriteLine("==================================");
Console.WriteLine("Ингредиенты:");
Console.ReadLine();
Console.WriteLine("- Кофе молотый - 2 чайные ложки");
Console.ReadLine();
Console.WriteLine("- Вода - 200 мл");
Console.ReadLine();
Console.WriteLine("- Сахар - по вкусу");
Console.ReadLine();
Console.WriteLine("==================================");
Console.WriteLine("1. Засыпать кофе в турку или кофеварку.");
Console.ReadLine();
Console.WriteLine("2. Залить холодной водой.");
Console.ReadLine();
Console.WriteLine("3. Варить на медленном огне, не доводя до кипения.");
Console.ReadLine();
Console.WriteLine("4. Перелить в чашку, добавить сахар.");
Console.WriteLine("==================================");
Console.WriteLine("Готово!");
Console.WriteLine("==================================");